/**
 * generate_tiles.cpp - Tile data code generator
 * 
 * This tool reads binary PT files from the original game data and generates
 * C++ code with hex-encoded tile arrays. This converts the Stage 1 runtime-loaded
 * tile data into Stage 2 code-based tile data.
 * 
 * Usage:
 *   cd /path/to/comic-modernization
 *   g++ -std=c++17 -o tools/generate_tiles tools/generate_tiles.cpp
 *   ./tools/generate_tiles
 * 
 * Output: src/level_tiles.cpp
 * 
 * This removes the runtime dependency on PT files - all tile data is now
 * compiled-in as C++ hex literals.
 */

#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include <cstdint>

/* Level names in order */
static const char* level_names[] = {
    "LAKE", "FOREST", "SPACE", "BASE", "CAVE", "SHED", "CASTLE", "COMP"
};

static const char* level_names_lower[] = {
    "lake", "forest", "space", "base", "cave", "shed", "castle", "comp"
};

/* PT file structure */
struct pt_file_t {
    uint16_t width;
    uint16_t height;
    uint8_t tiles[128 * 10];
};

/**
 * Read a single PT file
 */
bool read_pt_file(const std::string& filepath, pt_file_t& pt) {
    std::ifstream file(filepath, std::ios::binary);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open " << filepath << std::endl;
        return false;
    }
    
    file.read(reinterpret_cast<char*>(&pt.width), sizeof(uint16_t));
    file.read(reinterpret_cast<char*>(&pt.height), sizeof(uint16_t));
    
    if (!file) {
        std::cerr << "Error: Failed to read header from " << filepath << std::endl;
        return false;
    }
    
    if (pt.width != 128 || pt.height != 10) {
        std::cerr << "Error: Invalid dimensions in " << filepath 
                  << ": " << pt.width << "x" << pt.height << std::endl;
        return false;
    }
    
    file.read(reinterpret_cast<char*>(pt.tiles), 128 * 10);
    if (!file) {
        std::cerr << "Error: Failed to read tile data from " << filepath << std::endl;
        return false;
    }
    
    return true;
}

/**
 * Generate C++ code for tile arrays
 */
void write_cpp_header(std::ofstream& out) {
    out << "/**\n";
    out << " * level_tiles.cpp - Auto-generated tile data\n";
    out << " *\n";
    out << " * This file is GENERATED by tools/generate_tiles.cpp\n";
    out << " * Do NOT edit manually. Regenerate by running:\n";
    out << " *   cd /path/to/comic-modernization\n";
    out << " *   g++ -std=c++17 -o tools/generate_tiles tools/generate_tiles.cpp\n";
    out << " *   ./tools/generate_tiles\n";
    out << " *\n";
    out << " * Contains tile map data for all 8 levels, 3 stages each (24 total).\n";
    out << " * Embedded as C++ hex arrays to eliminate runtime file I/O.\n";
    out << " */\n\n";
    out << "#include \"level.h\"\n\n";
}

/**
 * Write a single tile array to C++ code
 */
void write_tile_array(std::ofstream& out, const std::string& level_name_lower, 
                      int stage_num, const uint8_t* tiles) {
    out << "/* " << level_name_lower << " Stage " << stage_num << " - Tile Map */\n";
    out << "const uint8_t " << level_name_lower << "_stage_" << stage_num 
        << "_tiles[128 * 10] = {\n";
    
    /* Write tiles in 16-byte rows for readability */
    for (int i = 0; i < 128 * 10; i++) {
        if (i > 0 && i % 16 == 0) {
            out << "\n";
        }
        out << "0x" << std::hex << std::setw(2) << std::setfill('0') 
            << static_cast<int>(tiles[i]) << std::dec;
        if (i < 128 * 10 - 1) {
            out << ", ";
        }
    }
    out << "\n};\n\n";
}

int main(int argc, char* argv[]) {
    std::string base_path = ".";
    
    /* Allow specifying the path to the game directory */
    if (argc > 1) {
        base_path = argv[1];
    }
    
    std::string original_dir = base_path + "/original";
    std::string output_file = base_path + "/src/level_tiles.cpp";
    
    /* Verify original directory exists */
    struct stat st;
    if (stat(original_dir.c_str(), &st) != 0 || !S_ISDIR(st.st_mode)) {
        std::cerr << "Error: Directory not found: " << original_dir << std::endl;
        std::cerr << "Usage: " << argv[0] << " [path_to_comic-modernization]" << std::endl;
        std::cerr << "  Example: ./tools/generate_tiles ." << std::endl;
        return 1;
    }
    
    std::cout << "Reading PT files from: " << original_dir << std::endl;
    std::cout << "Generating output to: " << output_file << std::endl;
    
    /* Open output file */
    std::ofstream out_file(output_file);
    if (!out_file.is_open()) {
        std::cerr << "Error: Cannot open output file: " << output_file << std::endl;
        return 1;
    }
    
    /* Write header */
    write_cpp_header(out_file);
    
    /* Process all levels and stages */
    int files_processed = 0;
    int files_failed = 0;
    
    for (int level_num = 0; level_num < 8; level_num++) {
        for (int stage_num = 0; stage_num < 3; stage_num++) {
            std::string filename = original_dir + "/" + level_names[level_num] 
                                 + std::to_string(stage_num) + ".PT";
            
            pt_file_t pt;
            if (read_pt_file(filename, pt)) {
                write_tile_array(out_file, level_names_lower[level_num], stage_num, pt.tiles);
                files_processed++;
                std::cout << "✓ " << filename << std::endl;
            } else {
                files_failed++;
                std::cout << "✗ " << filename << std::endl;
            }
        }
    }
    
    out_file.close();
    
    std::cout << "\nGeneration complete: " << files_processed << " files processed";
    if (files_failed > 0) {
        std::cout << ", " << files_failed << " failed";
    }
    std::cout << std::endl;
    
    if (files_failed > 0 && files_failed == 24) {
        std::cerr << "Error: No PT files found. Cannot generate tile data." << std::endl;
        return 1;
    }
    
    std::cout << "Output: " << output_file << std::endl;
    return files_failed > 0 ? 1 : 0;
}
