#!/usr/bin/env python3

# The sound format is an array of pairs
#   uint16_t frequency_divisor
#   uint16_t duration
# The frequency divisors divide the PIT base frequency of 1193182 Hz.
# Duration is counted in units of approximately 1/18.2 seconds (one tick of IRQ 0).
# A frequency_divisor of 0x0028 indicates a rest.
# The end of the table is marked with frequency_divisor == 0.

import getopt
import sys
import wave

BASE_FREQ = 1193182.
DIV_FREQ = BASE_FREQ / 65536.
FRAME_RATE = 48000

def read_uint16(f):
    b = f.read(2)
    if len(b) != 2:
        raise ValueError("unexpected EOF")
    return (b[1]<<8) + b[0]

def read_freq_table(f):
    t = []
    while True:
        freq = read_uint16(f)
        if freq == 0:
            break
        duration = read_uint16(f)
        for _ in range(duration):
            t.append(freq)
    return t

def square_wave(p):
    if p % 1.0 < 0.5:
        return 0
    else:
        return 1

def save_sound_file(t, filename):
    w = wave.open(filename, "wb")
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(FRAME_RATE)
    c = 0
    p = 0.0
    while True:
        s = c / FRAME_RATE
        i = int(s * DIV_FREQ)
        if i >= len(t):
            break

        if t[i] <= 0x28:
            x = 0
        else:
            x = int((square_wave(p) - 0.5) * 32767)
        w.writeframesraw(bytes([x & 0xff, (x>>8) & 0xff]))

        cur_freq = BASE_FREQ / t[i]
        p = (p + cur_freq / FRAME_RATE) % 1.0
        c += 1
    w.close()

def process(f, offset):
    f.seek(offset)
    return read_freq_table(f)

_, args = getopt.gnu_getopt(sys.argv[1:], "")
filename, offset, output_filename = args
offset = int(offset, base=0)
with open(filename, "rb") as f:
    freq_table = process(f, offset)
save_sound_file(freq_table, output_filename)
